### ISSUE TITLE
Error thrown for example WNUT-17 code

### ISSUE THREAD

**Issue by alanakbik** [flairNLP/transformer-ranker#4] opened 2024-10-23 14:59 UTC
I tried running: 

```python
from datasets import load_dataset
from transformer_ranker import TransformerRanker, prepare_popular_models

# Load the WNUT-17 dataset of English tweets annotated with NER labels
dataset_ner = load_dataset('leondz/wnut_17')

# Load a list of popular 'base' models
language_models = prepare_popular_models('base')

# Initialize the Ranker, but also let it know what the text and label column is
ranker_ner = TransformerRanker(dataset_ner,
                               dataset_downsample=0.7,
                               )

results_ner = ranker_ner.run(language_models, batch_size=64)

# Inspect results
print(results_ner)
```

but it throws an error when it comes to the SpanBERT model: 

```console
Retrieving Embeddings : 100%|██████████| 63/63 [00:11<00:00,  5.46it/s]
Estimating Performance: 100%|██████████| 1/1 [00:01<00:00,  1.99s/it]
transformer_ranker:distilbert-base-cased, estimated score: 1.0396
Retrieving Embeddings : 100%|██████████| 63/63 [00:10<00:00,  5.91it/s]
Estimating Performance: 100%|██████████| 1/1 [00:01<00:00,  2.00s/it]
transformer_ranker:typeform/distilroberta-base-v2, estimated score: 1.683
Retrieving Embeddings : 100%|██████████| 63/63 [00:19<00:00,  3.19it/s]
Estimating Performance: 100%|██████████| 1/1 [00:02<00:00,  2.01s/it]
transformer_ranker:bert-base-cased, estimated score: 1.4285
Some weights of BertModel were not initialized from the model checkpoint at SpanBERT/spanbert-base-cased and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Retrieving Embeddings : 100%|██████████| 63/63 [00:18<00:00,  3.47it/s]
Estimating Performance:   0%|          | 0/1 [00:00<?, ?it/s]

---------------------------------------------------------------------------

IndexError                                Traceback (most recent call last)

[<ipython-input-6-c3958f20f358>](https://localhost:8080/#) in <cell line: 15>()
     13                                )
     14 
---> 15 results_ner = ranker_ner.run(language_models, batch_size=64)
     16 
     17 # Inspect results

2 frames

[/usr/local/lib/python3.10/dist-packages/transformer_ranker/estimators/hscore.py](https://localhost:8080/#) in fit(self, features, labels)
     58         for i in range(n_classes):
     59             mask = labels == i
---> 60             Ef_i = features[mask].mean(dim=0)
     61             g[i] = Ef_i * torch.sqrt(mask.sum())
     62 

IndexError: The shape of the mask [71716] at index 0 does not match the shape of the indexed tensor [71712, 768] at index 0
```

I'm using a fresh Google Colab notebook with a T4 GPU and Python 3.10.12.

**Comment by lukasgarbas** [comment] 2024-10-27 23:19
Thanks for reporting! The issue is now resolved in the main branch. Changes will be included in the next pip drop.

**Closed** 2024-11-12 11:14 UTC
